"""update profile fields

Revision ID: 1e314e978151
Revises: b693a85e69b0
Create Date: 2026-08-11 10:06:13.091373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e314e978151'
down_revision: Union[str, Sequence[str], None] = 'b693a85e69b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('shopping_frequency', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_shopping', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('sustainable_fashion', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('chest_cm', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('waist_cm', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('hip_cm', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('shoulder_cm', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('sleeve_length_cm', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('shoe_size', sa.Float(), nullable=True))
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_user_profiles_body_type_id'), 'user_profiles', ['body_type_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_fit_preference_id'), 'user_profiles', ['fit_preference_id'], unique=False)
    op.drop_constraint(op.f('user_profiles_favorite_color_id_fkey'), 'user_profiles', type_='foreignkey')
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    op.drop_column('user_profiles', 'favorite_color_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('favorite_color_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_profiles_favorite_color_id_fkey'), 'user_profiles', 'colors', ['favorite_color_id'], ['id'])
    op.drop_index(op.f('ix_user_profiles_fit_preference_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_body_type_id'), table_name='user_profiles')
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('user_profiles', 'shoe_size')
    op.drop_column('user_profiles', 'sleeve_length_cm')
    op.drop_column('user_profiles', 'shoulder_cm')
    op.drop_column('user_profiles', 'hip_cm')
    op.drop_column('user_profiles', 'waist_cm')
    op.drop_column('user_profiles', 'chest_cm')
    op.drop_column('user_profiles', 'sustainable_fashion')
    op.drop_column('user_profiles', 'preferred_shopping')
    op.drop_column('user_profiles', 'shopping_frequency')
    op.drop_column('user_profiles', 'budget')
    # ### end Alembic commands ###
