"""add youcam fields to skin analysis

Revision ID: 6d3174e212d9
Revises: 5bc564fb2bbf
Create Date: 2026-08-11 22:24:17.172599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d3174e212d9'
down_revision: Union[str, Sequence[str], None] = '5bc564fb2bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_analysis_history', sa.Column('youcam_task_id', sa.String(length=255), nullable=True))
    op.add_column('skin_analysis_history', sa.Column('analysis_status', sa.String(length=50), nullable=False))
    op.add_column('skin_analysis_history', sa.Column('raw_result', sa.JSON(), nullable=True))
    op.alter_column('skin_analysis_history', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_skin_analysis_history_analysis_status'), 'skin_analysis_history', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_skin_analysis_history_youcam_task_id'), 'skin_analysis_history', ['youcam_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skin_analysis_history_youcam_task_id'), table_name='skin_analysis_history')
    op.drop_index(op.f('ix_skin_analysis_history_analysis_status'), table_name='skin_analysis_history')
    op.alter_column('skin_analysis_history', 'analyzed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('skin_analysis_history', 'raw_result')
    op.drop_column('skin_analysis_history', 'analysis_status')
    op.drop_column('skin_analysis_history', 'youcam_task_id')
    # ### end Alembic commands ###
