"""add skincare recommendation fields

Revision ID: fcb07c8e02a4
Revises: 6d3174e212d9
Create Date: 2026-08-15 19:45:42.071969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb07c8e02a4'
down_revision: Union[str, Sequence[str], None] = '6d3174e212d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_analysis_history', sa.Column('recommended_routine', sa.JSON(), nullable=True))
    op.add_column('skin_analysis_history', sa.Column('recommended_ingredients', sa.JSON(), nullable=True))
    op.add_column('skin_analysis_history', sa.Column('recommended_products', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skin_analysis_history', 'recommended_products')
    op.drop_column('skin_analysis_history', 'recommended_ingredients')
    op.drop_column('skin_analysis_history', 'recommended_routine')
    # ### end Alembic commands ###
