# Generated by Django 4.2.30 on 2026-08-17 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default='false')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TOKEN', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
