# Generated by Django 4.2.30 on 2026-08-17 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylesenseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIStylistSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_sessions', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'ai_stylist_sessions',
            },
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='wardrobe/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'wardrobe_items',
            },
        ),
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_photo', models.ImageField(upload_to='try_on/originals/')),
                ('result_photo', models.ImageField(blank=True, null=True, upload_to='try_on/results/')),
                ('outfit_source', models.CharField(default='My Wardrobe', max_length=50)),
                ('outfit_name', models.CharField(blank=True, max_length=100)),
                ('match_score', models.IntegerField(default=0)),
                ('skin_tone_score', models.IntegerField(default=0)),
                ('body_shape_score', models.IntegerField(default=0)),
                ('occasion_score', models.IntegerField(default=0)),
                ('season_score', models.IntegerField(default=0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tryons', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'virtual_try_ons',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('System', 'System')], default='Light', max_length=10)),
                ('accent_color', models.CharField(default='Purple', max_length=20)),
                ('notify_ai_analysis', models.BooleanField(default=True)),
                ('notify_weekly_report', models.BooleanField(default=True)),
                ('notify_product_recommendations', models.BooleanField(default=True)),
                ('notify_wardrobe_suggestions', models.BooleanField(default=True)),
                ('notify_new_features', models.BooleanField(default=True)),
                ('save_uploaded_photos', models.BooleanField(default=True)),
                ('ai_personalization', models.BooleanField(default=True)),
                ('anonymous_analytics', models.BooleanField(default=True)),
                ('face_detection_permission', models.BooleanField(default=True)),
                ('location_access', models.BooleanField(default=False)),
                ('ai_personality', models.CharField(default='Fashion Expert', max_length=50)),
                ('response_length', models.CharField(default='Short', max_length=20)),
                ('creativity_level', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('login_alerts', models.BooleanField(default=True)),
                ('show_active_sessions', models.BooleanField(default=True)),
                ('remember_trusted_devices', models.BooleanField(default=True)),
                ('biometric_authentication', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('tagline', models.CharField(default='AI Fashion Enthusiast', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('fit_preference', models.CharField(blank=True, max_length=50)),
                ('skin_tone', models.CharField(blank=True, max_length=50)),
                ('skin_type', models.CharField(blank=True, max_length=50)),
                ('skin_concerns', models.TextField(blank=True)),
                ('style_preferences', models.JSONField(blank=True, default=list)),
                ('shopping_budget', models.CharField(blank=True, max_length=50)),
                ('shopping_frequency', models.CharField(blank=True, max_length=50)),
                ('preferred_shopping', models.CharField(blank=True, max_length=50)),
                ('sustainable_fashion', models.BooleanField(default=False)),
                ('favorite_brands', models.JSONField(blank=True, default=list)),
                ('chest_cm', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('hip_cm', models.FloatField(blank=True, null=True)),
                ('shoulder_cm', models.FloatField(blank=True, null=True)),
                ('sleeve_length_cm', models.FloatField(blank=True, null=True)),
                ('shoe_size', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='SkinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_photo', models.ImageField(upload_to='skin_analysis/')),
                ('overall_score', models.IntegerField(default=0)),
                ('hydration', models.IntegerField(default=0)),
                ('texture', models.IntegerField(default=0)),
                ('brightness', models.IntegerField(default=0)),
                ('acne_reduction', models.IntegerField(default=0)),
                ('detected_concerns', models.JSONField(default=list)),
                ('copilot_summary', models.TextField(blank=True)),
                ('morning_routine', models.JSONField(default=list)),
                ('night_routine', models.JSONField(default=list)),
                ('recommended_ingredients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_analyses', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'skin_analyses',
            },
        ),
        migrations.CreateModel(
            name='OutfitCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='collections', to='stylesenseapp.wardrobeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_collections', to='stylesenseapp.user_login')),
            ],
            options={
                'db_table': 'outfit_collections',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI Stylist')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='stylesenseapp.aistylistsession')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
    ]
