# Generated by Django 4.2.30 on 2026-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylesenseapp', '0002_aistylistsession_wardrobeitem_virtualtryon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skinanalysis',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='user_login',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
